# Generated by Django 5.1.6 on 2025-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frais',
            name='type_frais',
            field=models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Annuel', 'Annuel'), ('Occasionnel', 'Occasionnel')], max_length=20),
        ),
    ]
