# Generated by Django 5.2.5 on 2025-08-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
    ]
